version: "3"
services:
  ipfsd:
    build: ipfsd/
    user: "ipfs:users"
    volumes:
      - ipfsd/ipfsdb:/data/ipfs
    ports:
      - "4001:4001" #p2p
      #- "5001:5001" #ipfs webgui
    container_name: ipfsd
    restart: always
  dogecoin:
    build: dogecoin_service/
    ports:
      - "22556:22556" #p2p
    volumes:
      - dogecoin_service/dogecoindata:/data/dogecoin
    container_name: dogecoin
    user: "dogecoind:dogecoind"
    restart: always
  mspreader:
    build: reader/
    user: "www-data:www-data"
    ports:
      - 8080:8081
    container_name: msp_reader
    depends_on:
      - ipfsd
      - dogecoin
    restart: always
